### ISSUE TITLE
get_maximum_partition_size returning zero when there is plenty of space.

### ISSUE THREAD

**Issue by glennswest** [cecton/gptman#44]
When I call:
 let max_size : u64 =  gpt.get_maximum_partition_size().unwrap_or(0);
Im getting zero. When I know there a huge amount of space left.
This is the starting point:
https://gist.github.com/glennswest/d79bf8ffc062d1e1a85491b20f3f0f37

Test run:

Device       Start     End Sectors  Size Type
/dev/sda1     2048  788479  786432  384M Linux filesystem
/dev/sda2   788480 1048575  260096  127M EFI System
/dev/sda3  1048576 1050623    2048    1M BIOS boot
/dev/sda4  1050624 7325662 6275039    3G Linux filesystem

The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
Starting 4 partition Test Case
http://ctl.gsw.lo//rhcos/rhcos-4.5.0-rc.7-x86_64-metal.x86_64.raw.gz
Downloading image from http://ctl.gsw.lo/rhcos/rhcos-4.5.0-rc.7-x86_64-metal.x86_64.raw.gz
Downloading signature from http://ctl.gsw.lo/rhcos/rhcos-4.5.0-rc.7-x86_64-metal.x86_64.raw.gz.sig
Failed to fetch signature: fetching signature URL
Signature not found; skipping verification as requested
Extra Partitions = 0

> Read disk 853.1 MiB/853.1 MiB (100%)   
Remaining Disk 0

Last Usable Sector: 7325662

Note:
[root@pxe coreos-installer]# sfdisk -V /dev/sda
GPT PMBR size mismatch (7325695 != 1843199999) will be corrected by write.
/dev/sda:
No errors detected.
Header version: 1.0
Using 4 out of 128 partitions.
A total of 1835876318 free sectors is available in 2 segments (the largest is 875.4 GiB).
[root@pxe coreos-installer]#

**Comment by cecton** [comment]
It looks like gptman detected that your disk has a size of 7325695 instead of 1843199999.

gptman uses Seek to get the size of the disk. I believe this should work properly (I don't see how it could fail).

Is it possible that you opened a partition instead of the disk with gptman? (sounds silly I know but I do typos all the time)

Can you show me the command you use to start gptman?

**Comment by cecton** [comment]
Never mind, I'm pretty wild guess of what is your issue.

You're restoring a system from an image and that image is made for a disk of 800mb. By default, gptman uses what is specified in the GPT. So you have 0 bytes left.

To fix that you can update the GPT instance right after reading it. Use `update_from` and this will update the last available sector of the partition table.

**Comment by cecton** [comment]
I will probably find a way to improve the API on that aspect so it's a bit less surprising.

**Comment by glennswest** [comment]
Yes, its part of the install process. So it copies a image, then want to be able to use gptman to do further partition work. So the last block needs a update. Does update_from need the handle open for write?

**Comment by cecton** [comment]
Nope! As you can see in the doc, it's only using Seek (not even Read).

**Comment by glennswest** [comment]
Mind to give me a hint.

 fn update_gpt_headers(disk:&str) {
    let mut f = std::fs::File::open(disk.to_string())
      .expect("Cannot open disk");
    let gpt = gptman::GPT::find_from(&mut f)
      .expect("GPT Partitions not found");
    drop(f);

    let mut f = fs::OpenOptions::new().write(true).open(disk.to_string())
                .expect("Cannot open device for write");
    let mut gpt = gptman::GPT::find_from(&mut f)
      .expect("GPT Partitions not found");
    gpt.gptman::GPT::update_from(&mut gpt);
   drop (f) ;
}

**Comment by glennswest** [comment]
This is closer. 
But still not quite right:

fn update_gpt_headers(disk:&str) {

    let mut f = fs::OpenOptions::new().write(true).open(disk.to_string())
                .expect("Cannot open device for write");
    let mut gptheader = gptman::GPT::read_from(&mut f)
      .expect("GPT Partitions not found");
    gptheader.update_from();
   drop (f) ;
}

**Comment by cecton** [comment]
read_from => read the GPT, make a GPT instance in memory
update_from => take a disk, update the GPT in memory
write_into => actually write the GPT on disk

Nothing writes on disk, only the write_into does.

**Comment by glennswest** [comment]
cool.

fn update_gpt_headers(disk:&str) {

    let mut f = fs::OpenOptions::new().write(true).read(true).open(disk.to_string())
                .expect("Cannot open device for write");
    let mut gpt = gptman::GPT::find_from(&mut f)
      .expect("GPT Partitions not found");
    gpt.header.update_from(&mut f,512)
          .expect("Update of Disk Headers Failed");

    gpt.write_into(&mut f)
        .expect("Cannot write data into gpt");
    drop (f) ;
}

**Comment by glennswest** [comment]
Yep, that got me a day plus when I was adding partitions. 
The examples dont show that step.

**Comment by cecton** [comment]
purrfect! You can even take the sector size from the gpt instance so you don't change it by mistake https://docs.rs/gptman/0.6.3/gptman/struct.GPT.html#structfield.sector_size

**Comment by cecton** [comment]
I will improve the doc on that, thank you for the feedback!

**Comment by glennswest** [comment]
Resolved:
> Read disk 853.1 MiB/853.1 MiB (100%)   
Remaining Disk 1835872256

Last Usable Sector: 1843199966

Disk Size 1249934756

Install complete.

Thanks so much for the help. 
And it help me resolve a higher level problem as well in the installer.

**Comment by glennswest** [comment]
Final form:

fn update_gpt_headers(disk:&str) {

    let mut f = fs::OpenOptions::new().write(true).read(true).open(disk.to_string())
                .expect("Cannot open device for write");
    let mut gpt = gptman::GPT::find_from(&mut f)
      .expect("GPT Partitions not found");
    gpt.header.update_from(&mut f,gpt.sector_size)
          .expect("Update of Disk Headers Failed");

    gpt.write_into(&mut f)
        .expect("Cannot write data into gpt");
    drop (f) ;
}

And thanks so much for the help.
